# Generated by Django 5.2.17 on 2026-09-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('APPLICATION', 'Application'), ('API', 'API'), ('SERVER', 'Server'), ('DATABASE', 'Database'), ('WORKSTATION', 'Workstation'), ('FILE_SERVER', 'File Server'), ('VPN_GATEWAY', 'VPN Gateway'), ('CLOUD_SERVICE', 'Cloud Service'), ('CI_CD', 'CI/CD System'), ('EMAIL_SERVER', 'Email Server'), ('DOMAIN_CONTROLLER', 'Domain Controller'), ('NETWORK_DEVICE', 'Network Device'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_internet_exposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('CONNECTS_TO', 'Connects To'), ('CALLS', 'Calls'), ('READS', 'Reads'), ('WRITES', 'Writes'), ('AUTHENTICATES_TO', 'Authenticates To'), ('DEPENDS_ON', 'Depends On')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.asset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.asset')),
            ],
            options={
                'ordering': ['source_id', 'target_id', 'relationship_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_asset_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relationship_type'), name='unique_asset_relationship'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='relationship_source_not_target'),
        ),
    ]
