# Generated by Django 5.2.17 on 2026-09-24 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('DMZ', 'DMZ'), ('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted'), ('MANAGEMENT', 'Management'), ('CLOUD', 'Cloud'), ('ENDPOINT', 'Endpoint'), ('OTHER', 'Other')], default='INTERNAL', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='environment',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('TEST', 'Test'), ('DEVELOPMENT', 'Development'), ('OTHER', 'Other')], default='PRODUCTION', max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='relationship',
            name='protocol',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='relationship',
            name='requires_authentication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(condition=models.Q(('port__isnull', True), models.Q(('port__gte', 1), ('port__lte', 65535)), _connector='OR'), name='relationship_valid_port'),
        ),
        migrations.AddField(
            model_name='networkzone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_zones', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.networkzone'),
        ),
        migrations.AddConstraint(
            model_name='networkzone',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_zone_name_per_organization'),
        ),
    ]
