# Generated by Django 5.2.17 on 2026-10-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_networkzone_asset_environment_asset_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='required_source_privilege',
            field=models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('HIGH', 'High')], default='LOW', max_length=8),
        ),
    ]
