# Generated by Django 5.2.17 on 2026-10-01 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_relationship_required_source_privilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, help_text='Optional CVE or internal vulnerability identifier.', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('attack_vector', models.CharField(choices=[('NETWORK', 'Network'), ('ADJACENT', 'Adjacent'), ('LOCAL', 'Local'), ('PHYSICAL', 'Physical')], max_length=16)),
                ('privileges_required', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('HIGH', 'High')], default='NONE', max_length=8)),
                ('grants_privilege', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('bypasses_authentication', models.BooleanField(default=False, help_text='Whether this modeled vulnerability can bypass an authentication requirement on a relationship.')),
                ('is_exploitable', models.BooleanField(default=True, help_text='Whether RiftTrace should treat this vulnerability as usable in the current model.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__name', 'title'],
            },
        ),
    ]
