# Generated by Django 5.2.17 on 2026-10-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_relationship_required_source_privilege'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('impact_description', models.TextField(blank=True, help_text='Human-readable description of the potential business consequence if this process is affected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_processes', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_level', models.CharField(choices=[('SUPPORTING', 'Supporting'), ('IMPORTANT', 'Important'), ('ESSENTIAL', 'Essential')], default='IMPORTANT', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_process_dependencies', to='assets.asset')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_dependencies', to='business.businessprocess')),
            ],
            options={
                'ordering': ['business_process__name', 'asset__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessprocess',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_business_process_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='businessprocessdependency',
            constraint=models.UniqueConstraint(fields=('business_process', 'asset'), name='unique_asset_dependency_per_business_process'),
        ),
    ]
